# Binded to OpenClaw container in read-only ("ro") mode to prevent adding different nameservers
# Change DNS nameserver here if your firewall container is running a different DNS server, 
# or if you want to use an external DNS server in OpenClaw instead (not recommended for security reasons)
nameserver 10.0.0.1
options ndots:0